name: Low Dependencies
on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * 0'

jobs:
    locked:
        name: Node ${{ matrix.node-versions }} - ${{ matrix.os }}
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-2019]
                node-versions: [ '12', '16']

        steps:
            -   name: Checkout
                uses: actions/checkout@v2.0.0

            -   name: Node ${{matrix.node-versions}}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{matrix.node-versions}}

            -   name: Remove Lock File
                run: rm yarn.lock

            -   name: Force Lowest Dependencies
                run: node ./scripts/force-lowest-dependencies

            -   name: Install Yarn Dependencies
                run: yarn install

            -   name: Show Installed Versions
                run: yarn list --depth=0

            -   name: Run Tests
                run: yarn test
